# Generated by Django 6.0.2 on 2026-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('current_complaints', models.IntegerField()),
                ('historical_avg', models.IntegerField(help_text='Historical trend for early warning')),
            ],
        ),
    ]
